# Generated by Django 4.1.7 on 2023-04-11 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField(default=datetime.date(2023, 4, 11))),
                ('transactions', models.TextField(verbose_name='Transactions')),
                ('proof', models.IntegerField()),
                ('previous_hash', models.TextField(verbose_name='Hash')),
            ],
        ),
    ]
