# Generated by Django 4.1.7 on 2023-04-15 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.TextField(default=datetime.date(2023, 4, 15)),
        ),
    ]
