# Generated by Django 4.1.7 on 2023-04-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[('0', 'food'), ('1', 'medicine'), ('2', 'other')], default=2),
        ),
    ]
