# Generated by Django 4.1.7 on 2023-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_product',
            field=models.CharField(max_length=1000),
        ),
    ]
