# Generated by Django 4.1.7 on 2023-05-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_product_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(0, 'food'), (1, 'medicine'), (2, 'device'), (3, 'other')], default=2),
        ),
    ]
